In [30]:
import pandas as pd
df = pd.read_csv("customer_shopping_behavior.csv")
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,1,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36,Cash,Weekly
1,2,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20,Debit Card,Quarterly
2,3,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18,Cash,Monthly
3,4,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25,Cash,Annually
4,5,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17,Credit Card,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5046,5096,19,Female,Backpack,Accessories,53.0,Iowa,M,Gold,Spring,3.4,No,Standard,No,31,Debit Card,Weekly
5047,5097,70,Female,Skirt,Clothing,27.0,North Dakota,M,White,Summer,3.2,No,Standard,No,15,Bank Transfer,Every 3 Months
5048,5098,43,Female,Sneakers,Footwear,52.0,Maryland,L,Gold,Summer,4.6,No,Standard,No,10,Credit Card,Bi-Weekly
5049,5099,62,Male,Blouse,Clothing,71.0,Maine,M,Cyan,Summer,3.3,No,Free Shipping,No,5,Bank Transfer,Every 3 Months
5050,median(customer),median(Age),median(Gender),median(Item Purchased),median(Category),0.0,median(Location),NaN,median(Color),median(Season),0.0,median(Subscription),median(Shipping Type),median(Discount Applied),0,median(Cash),Quarterly

In [31]:
df.shape

(5051, 17)

In [32]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,1,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36,Cash,Weekly
1,2,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20,Debit Card,Quarterly
2,3,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18,Cash,Monthly
3,4,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25,Cash,Annually
4,5,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17,Credit Card,Weekly

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5051 entries, 0 to 5050
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5051 non-null   object
 1   Age                     5051 non-null   object
 2   Gender                  5051 non-null   object
 3   Item Purchased          5051 non-null   object
 4   Category                5051 non-null   object
 5   Purchase Amount (USD)   5051 non-null   float64
 6   Location                5051 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5051 non-null   object
 9   Season                  5051 non-null   object
 10  Review Rating           5051 non-null   float64
 11  Subscription Status     5051 non-null   object
 12  Shipping Type           5051 non-null   object
 13  Discount Applied        5051 non-null   object
 14  Previous Purchases      5051 non-null   int64
 15  Payment Method          5051 non-null   object
 16  Frequency of Purchases  5051 non-null   object
dtypes: float64(2), int64(1), object(14)
memory usage: 671.0+ KB

In [34]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,5051,5051,5051,5051,5051,5051.000000,5051,4680,5051,5051,5051.000000,5051,5051,5051,5051.000000,5051,5051
unique,5001,54,4,31,6,NaN,55,4,26,6,NaN,3,7,3,NaN,7,7
top,3507,41,Male,Shirt,Clothing,NaN,New York,M,Black,Spring,NaN,No,Standard,No,NaN,Credit Card,Monthly
freq,2,114,3018,320,2130,NaN,337,1981,404,1280,NaN,3462,1213,2789,NaN,954,946
mean,NaN,NaN,NaN,NaN,NaN,128.801222,NaN,NaN,NaN,NaN,3.231004,NaN,NaN,NaN,22.480499,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,263.873922,NaN,NaN,NaN,NaN,1.439590,NaN,NaN,NaN,15.798514,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,33.000000,NaN,NaN,NaN,NaN,2.800000,NaN,NaN,NaN,8.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,59.000000,NaN,NaN,NaN,NaN,3.500000,NaN,NaN,NaN,22.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,85.000000,NaN,NaN,NaN,NaN,4.300000,NaN,NaN,NaN,36.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,1499.760000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN

In [35]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                      371
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [36]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Size'] = le.fit_transform(df['Size'])

In [37]:
df['Size'] = df.groupby('Category')['Size'].transform(lambda x: x.fillna(x.median()))

In [38]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [39]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,1,22,Female,T-shirt,Clothing,68.0,California,3,Olive,Winter,3.2,No,Standard,No,36,Cash,Weekly
1,2,51,Male,Sunglasses,Accessories,84.0,South Carolina,1,White,Spring,3.9,Yes,Free Shipping,Yes,20,Debit Card,Quarterly
2,3,18,Female,Shirt,Clothing,50.0,Montana,1,Black,Winter,3.1,No,2-Day Shipping,No,18,Cash,Monthly
3,4,22,Male,Gloves,Accessories,75.0,Illinois,0,Red,Fall,4.2,No,Store Pickup,No,25,Cash,Annually
4,5,40,Female,Jewelry,Accessories,80.0,Alabama,0,Yellow,Spring,3.6,No,Store Pickup,No,17,Credit Card,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5046,5096,19,Female,Backpack,Accessories,53.0,Iowa,1,Gold,Spring,3.4,No,Standard,No,31,Debit Card,Weekly
5047,5097,70,Female,Skirt,Clothing,27.0,North Dakota,1,White,Summer,3.2,No,Standard,No,15,Bank Transfer,Every 3 Months
5048,5098,43,Female,Sneakers,Footwear,52.0,Maryland,0,Gold,Summer,4.6,No,Standard,No,10,Credit Card,Bi-Weekly
5049,5099,62,Male,Blouse,Clothing,71.0,Maine,1,Cyan,Summer,3.3,No,Free Shipping,No,5,Bank Transfer,Every 3 Months
5050,median(customer),median(Age),median(Gender),median(Item Purchased),median(Category),0.0,median(Location),4,median(Color),median(Season),0.0,median(Subscription),median(Shipping Type),median(Discount Applied),0,median(Cash),Quarterly

In [40]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [41]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating_', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [42]:
df = df.rename(columns = {'purchase_amount_(usd)':'Purchased_Amount'})

In [43]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'Purchased_Amount', 'location', 'size', 'color', 'season',
       'review_rating_', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [44]:
df

,customer_id,age,gender,item_purchased,category,Purchased_Amount,location,size,color,season,review_rating_,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,1,22,Female,T-shirt,Clothing,68.0,California,3,Olive,Winter,3.2,No,Standard,No,36,Cash,Weekly
1,2,51,Male,Sunglasses,Accessories,84.0,South Carolina,1,White,Spring,3.9,Yes,Free Shipping,Yes,20,Debit Card,Quarterly
2,3,18,Female,Shirt,Clothing,50.0,Montana,1,Black,Winter,3.1,No,2-Day Shipping,No,18,Cash,Monthly
3,4,22,Male,Gloves,Accessories,75.0,Illinois,0,Red,Fall,4.2,No,Store Pickup,No,25,Cash,Annually
4,5,40,Female,Jewelry,Accessories,80.0,Alabama,0,Yellow,Spring,3.6,No,Store Pickup,No,17,Credit Card,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5046,5096,19,Female,Backpack,Accessories,53.0,Iowa,1,Gold,Spring,3.4,No,Standard,No,31,Debit Card,Weekly
5047,5097,70,Female,Skirt,Clothing,27.0,North Dakota,1,White,Summer,3.2,No,Standard,No,15,Bank Transfer,Every 3 Months
5048,5098,43,Female,Sneakers,Footwear,52.0,Maryland,0,Gold,Summer,4.6,No,Standard,No,10,Credit Card,Bi-Weekly
5049,5099,62,Male,Blouse,Clothing,71.0,Maine,1,Cyan,Summer,3.3,No,Free Shipping,No,5,Bank Transfer,Every 3 Months
5050,median(customer),median(Age),median(Gender),median(Item Purchased),median(Category),0.0,median(Location),4,median(Color),median(Season),0.0,median(Subscription),median(Shipping Type),median(Discount Applied),0,median(Cash),Quarterly

In [47]:
#create a column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']

df['age_group'] = pd.qcut(
    df['age'],
    q=4,
    labels=labels
)

In [45]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')

In [46]:
print(df['age'].dtype)

float64

In [48]:
df

,customer_id,age,gender,item_purchased,category,Purchased_Amount,location,size,color,season,review_rating_,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,22.0,Female,T-shirt,Clothing,68.0,California,3,Olive,Winter,3.2,No,Standard,No,36,Cash,Weekly,Young Adult
1,2,51.0,Male,Sunglasses,Accessories,84.0,South Carolina,1,White,Spring,3.9,Yes,Free Shipping,Yes,20,Debit Card,Quarterly,Middle-aged
2,3,18.0,Female,Shirt,Clothing,50.0,Montana,1,Black,Winter,3.1,No,2-Day Shipping,No,18,Cash,Monthly,Young Adult
3,4,22.0,Male,Gloves,Accessories,75.0,Illinois,0,Red,Fall,4.2,No,Store Pickup,No,25,Cash,Annually,Young Adult
4,5,40.0,Female,Jewelry,Accessories,80.0,Alabama,0,Yellow,Spring,3.6,No,Store Pickup,No,17,Credit Card,Weekly,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5046,5096,19.0,Female,Backpack,Accessories,53.0,Iowa,1,Gold,Spring,3.4,No,Standard,No,31,Debit Card,Weekly,Young Adult
5047,5097,70.0,Female,Skirt,Clothing,27.0,North Dakota,1,White,Summer,3.2,No,Standard,No,15,Bank Transfer,Every 3 Months,Senior
5048,5098,43.0,Female,Sneakers,Footwear,52.0,Maryland,0,Gold,Summer,4.6,No,Standard,No,10,Credit Card,Bi-Weekly,Adult
5049,5099,62.0,Male,Blouse,Clothing,71.0,Maine,1,Cyan,Summer,3.3,No,Free Shipping,No,5,Bank Transfer,Every 3 Months,Senior
5050,median(customer),NaN,median(Gender),median(Item Purchased),median(Category),0.0,median(Location),4,median(Color),median(Season),0.0,median(Subscription),median(Shipping Type),median(Discount Applied),0,median(Cash),Quarterly,NaN

In [49]:
frequency_days = {
    'Weekly': 7,
    'Bi-Weekly': 14,
    'Fortnightly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Every 3 Months': 90,
    'Annually': 365
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_days)

In [50]:
df['frequency_of_purchases'].head(10)

0            Weekly
1         Quarterly
2           Monthly
3          Annually
4            Weekly
5          Annually
6    Every 3 Months
7          Annually
8         Bi-Weekly
9           Monthly
Name: frequency_of_purchases, dtype: object

In [51]:
df

,customer_id,age,gender,item_purchased,category,Purchased_Amount,location,size,color,season,review_rating_,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,22.0,Female,T-shirt,Clothing,68.0,California,3,Olive,Winter,3.2,No,Standard,No,36,Cash,Weekly,Young Adult,7
1,2,51.0,Male,Sunglasses,Accessories,84.0,South Carolina,1,White,Spring,3.9,Yes,Free Shipping,Yes,20,Debit Card,Quarterly,Middle-aged,90
2,3,18.0,Female,Shirt,Clothing,50.0,Montana,1,Black,Winter,3.1,No,2-Day Shipping,No,18,Cash,Monthly,Young Adult,30
3,4,22.0,Male,Gloves,Accessories,75.0,Illinois,0,Red,Fall,4.2,No,Store Pickup,No,25,Cash,Annually,Young Adult,365
4,5,40.0,Female,Jewelry,Accessories,80.0,Alabama,0,Yellow,Spring,3.6,No,Store Pickup,No,17,Credit Card,Weekly,Adult,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5046,5096,19.0,Female,Backpack,Accessories,53.0,Iowa,1,Gold,Spring,3.4,No,Standard,No,31,Debit Card,Weekly,Young Adult,7
5047,5097,70.0,Female,Skirt,Clothing,27.0,North Dakota,1,White,Summer,3.2,No,Standard,No,15,Bank Transfer,Every 3 Months,Senior,90
5048,5098,43.0,Female,Sneakers,Footwear,52.0,Maryland,0,Gold,Summer,4.6,No,Standard,No,10,Credit Card,Bi-Weekly,Adult,14
5049,5099,62.0,Male,Blouse,Clothing,71.0,Maine,1,Cyan,Summer,3.3,No,Free Shipping,No,5,Bank Transfer,Every 3 Months,Senior,90
5050,median(customer),NaN,median(Gender),median(Item Purchased),median(Category),0.0,median(Location),4,median(Color),median(Season),0.0,median(Subscription),median(Shipping Type),median(Discount Applied),0,median(Cash),Quarterly,NaN,90

In [52]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "Pavan28126"     # the password you set during installation
host = "localhost"        # if running locally
port = "5432"             # default PostgreSQL port
database = "customer_behaviour"     # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"    # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behaviour'.